### ISSUE TITLE
TLS error when adding an engine

### ISSUE THREAD

**Issue by sybeck2k** [shipyard/shipyard#384] opened 2014-12-17 13:46 UTC
I've configured docker to accept connections over TLS. The connection is tested to be working via both curl and docker client:
```
> docker --tlsverify --tlscacert=../ca/ca.crt --tlscert=cert.pem  --tlskey=key.pem -H=<myhostname>:2376 version
Client version: 1.4.0
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 4595d4f
OS/Arch (client): linux/amd64
Server version: 1.4.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 4595d4f
```
and 
```
> curl -i -v --cacert ../ca/certs.pem -E cert.pem  --key key.pem https://<myhostname>:2376/images/json
[{" .... " }]
```

but when I try to create the engine in Shipyard with the same certificates (tested with both the pem and crt version of the CA) I get:
```
Get https://<myhostname>:2376/_ping: x509: failed to load system roots and no roots provided 
```

I'm running Shipyard from the docker image version 2.0.6.

**Comment by ehazlett** [comment] 2015-01-01 17:59
@sybeck2k @byxorna @gpmidi @jjmaes @Stono 

Ok I think the issue is fixed.  It was the engine health check that was causing all of the failures.  I've tested with boot2docker and its certificates and it works both from the web UI and the cli.  There are new builds pushed to `shipyard/shipyard` and `shipyard/shipyard-cli` with the updates.

Would you mind testing to confirm the fix?   Thanks!

**Comment by gpmidi** [comment] 2015-01-01 18:21
@ehazlett It works great. Thanks!

**Comment by ehazlett** [comment] 2015-01-01 18:34
@gpmidi awesome.  thanks for the feedback.  i'm going to wait until (hopefully) a couple others verify before closing.  thanks!

**Comment by gpmidi** [comment] 2015-01-01 18:35
Oh yeah, almost forgot: If they notice that it works but the list of containers doesn't show up then they just need to logout and login again.

**Comment by ehazlett** [comment] 2015-01-01 18:42
hmm ok -- that may be caching

**Comment by gpmidi** [comment] 2015-01-01 18:45
I tried ctrl-F5 without any luck; if it was caching it doesn't seem like it was on the browser side. Chrome's dev tools showed that the request to the container api was failing as unauthorized.

**Comment by ehazlett** [comment] 2015-01-01 19:21
interesting.  thx for the info.

**Comment by Stono** [comment] 2015-01-01 22:53
Hi,
With the :test image I can confirm I can add a https:// host fine :-)

Thanks for the prompt reply, let me know when you've tagged :latest 

Ta

**Comment by kadishmal** [comment] 2015-01-02 01:10
Waiting for the fix as well. Have the same problem.

**Comment by ehazlett** [comment] 2015-01-02 01:42
Wait, so the fix isn't working for you?  Did you try the
shipyard/shipyard:test image?

**Comment by kadishmal** [comment] 2015-01-02 02:02
I mean waiting on the main branch... having tried the test. Using 2.0.6.

**Comment by ehazlett** [comment] 2015-01-02 02:17
ah ok.  i will release a new version soon.

**Comment by ehazlett** [comment] 2015-01-02 04:20
`shipyard/shipyard:2.0.8` and `shipyard/shipyard-cli:2.0.8` pushed.

**Closed by ehazlett** 2015-01-02 04:20 UTC
Labels: bug

**Comment by beeyeas** [comment] 2015-05-05 18:55
*Adding Engine (my docker daemon) has been a pain with shipyard, i always get 
Error
Get http://10.a.x.12:5555/_ping: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

*Why would it try a TLS connection when i clearly mention "HTTP" in URL?
* I am not yet there with TLS , Adding SSL Cert, SSL Key and CA Cert in UI is not a suggested way.
