### ISSUE TITLE
How to add new nodes

### ISSUE THREAD

**Issue by ytc301** [shipyard/shipyard#601] opened 2015-09-16 02:08 UTC
How to add new nodes

**Comment by John-Lin** [comment] 2015-09-16 03:27
Duplicate of #599

**Comment by beyondblog** [comment] 2015-09-16 03:52
Reference：https://docs.docker.com/swarm/

:stuck_out_tongue_winking_eye: 

![image](https://cloud.githubusercontent.com/assets/3734587/9896015/28f0d064-5c69-11e5-9c90-d7fca3dcd335.png)

**Comment by ehazlett** [comment] 2015-09-16 04:00
Closing as a duplicate to #599

**Closed by ehazlett** 2015-09-16 04:00 UTC
