### ISSUE TITLE
no route to host 

### ISSUE THREAD

**Issue by bing6** [shipyard/shipyard#640] opened 2015-10-20 01:55 UTC
WARN[0001] Error creating connection dial tcp 172.17.0.9:28015: getsockopt: no route to host 
FATA[0001] no connections were made when creating the session 

This is what causes??

**Comment by RustJason** [comment] 2015-10-20 02:30
Too hard to say, How did you install shipyard?

**Comment by bing6** [comment] 2015-10-20 05:29
curl -s https://shipyard-project.com/deploy | bash -s

This is a relationship with the docker version?

**Comment by RustJason** [comment] 2015-10-20 09:20
Show me your ```docker ps -a``` ```docker version```

**Comment by johnny-wang86** [comment] 2015-10-20 10:35
I have similar problems


![1](https://cloud.githubusercontent.com/assets/5415121/10604753/3d44706a-7759-11e5-9193-547a7b46d48b.png)
![2](https://cloud.githubusercontent.com/assets/5415121/10604763/4a535af0-7759-11e5-863e-c74c228de82b.png)
![3](https://cloud.githubusercontent.com/assets/5415121/10604770/54150c82-7759-11e5-9211-fb37954ac1e0.png)

**Comment by RustJason** [comment] 2015-10-20 11:16
@johnny-wang86  show me inspect output of rethinkdb container. ```docker inspect 18e```

**Comment by ehazlett** [comment] 2015-10-20 13:36
Can you also post the Docker version you are using?

**Comment by bing6** [comment] 2015-10-21 00:35
INFO[0000] shipyard version 3.0.1                       
WARN[0001] Error creating connection dial tcp 172.17.0.91:28015: getsockopt: no route to host 
FATA[0001] no connections were made when creating the session 
INFO[0000] shipyard version 3.0.1                       
WARN[0001] Error creating connection dial tcp 172.17.0.91:28015: getsockopt: no route to host 
FATA[0001] no connections were made when creating the session 
INFO[0000] shipyard version 3.0.1                       
WARN[0001] Error creating connection dial tcp 172.17.0.91:28015: getsockopt: no route to host 
FATA[0001] no connections were made when creating the session 
INFO[0000] shipyard version 3.0.1                       
WARN[0001] Error creating connection dial tcp 172.17.0.91:28015: getsockopt: no route to host 
FATA[0001] no connections were made when creating the session 


[
{
    "Id": "e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875",
    "Created": "2015-10-20T11:59:38.001912365Z",
    "Path": "rethinkdb",
    "Args": [
        "--bind",
        "all"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 20280,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-10-20T11:59:38.860081585Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "84afe2b8ffc117382da1b23db65778cb57cf33584ef1550a72a72de1de37aa97",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "4dca9d870a45815c8562f786b007007bd3cdc44af3a840b39bb780080a37fd0a",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.91",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:5b",
        "NetworkID": "eda181dfc75f632540ac7bbbd24bddd00b6be9430fff0a0358d764f28194c391",
        "PortMapping": null,
        "Ports": {
            "28015/tcp": null,
            "29015/tcp": null,
            "8080/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/e085c4c2a5aa",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875/hostname",
    "HostsPath": "/var/lib/docker/containers/e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875/hosts",
    "LogPath": "/var/lib/docker/containers/e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875/e085c4c2a5aa1e13bdeecb61f78bd40e58ca5758907f8977f07447e56a032875-json.log",
    "Name": "/shipyard-rethinkdb",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/data": "/var/lib/docker/volumes/c1571b1ea07c19606cba8d70fdb1721d85ff5bae567f92b8bb509fa7ac70f401/_data"
    },
    "VolumesRW": {
        "/data": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "e085c4c2a5aa",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "28015/tcp": {},
            "29015/tcp": {},
            "8080/tcp": {}
        },
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "RETHINKDB_PACKAGE_VERSION=2.1.5+2~0jessie"
        ],
        "Cmd": [
            "rethinkdb",
            "--bind",
            "all"
        ],
        "Image": "rethinkdb",
        "Volumes": {
            "/data": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "/data",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by johnny-wang86** [comment] 2015-10-21 02:32
@RustJason 
docker inspect 18e
[
{
    "Id": "18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27",
    "Created": "2015-10-20T10:06:32.91621657Z",
    "Path": "rethinkdb",
    "Args": [
        "--bind",
        "all"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 6659,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-10-20T10:06:33.202820075Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "84afe2b8ffc117382da1b23db65778cb57cf33584ef1550a72a72de1de37aa97",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "0d793d97b801046e8ec928a0a555677d9608d1d8a060f9b6ca46c2767c0cc048",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.5",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:05",
        "NetworkID": "581f3a76b3282e7cf76ceaf2cdc9b0b7a7b4b63a6ee78b1aa64a7ffc68a5c920",
        "PortMapping": null,
        "Ports": {
            "28015/tcp": null,
            "29015/tcp": null,
            "8080/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/18e34ceb8339",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27/hostname",
    "HostsPath": "/var/lib/docker/containers/18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27/hosts",
    "LogPath": "/var/lib/docker/containers/18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27/18e34ceb83390f37f0e6e0a0607f57f5daa10e160f828368be19d13dc0942a27-json.log",
    "Name": "/shipyard-rethinkdb",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/data": "/var/lib/docker/volumes/4449cdaba9593b26cedd12196cd56ae4ef7135ede09ac8545f7aa5fa2faee006/_data"
    },
    "VolumesRW": {
        "/data": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "18e34ceb8339",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "28015/tcp": {},
            "29015/tcp": {},
            "8080/tcp": {}
        },
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "RETHINKDB_PACKAGE_VERSION=2.1.5+2~0jessie"
        ],
        "Cmd": [
            "rethinkdb",
            "--bind",
            "all"
        ],
        "Image": "rethinkdb",
        "Volumes": {
            "/data": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "/data",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by johnny-wang86** [comment] 2015-10-21 02:40
@ehazlett 
Docker version 1.7.1 ,kernel version 3.10.90-1 or  3.10.5-3

**Comment by RustJason** [comment] 2015-10-21 03:00
@bing6 @johnny-wang86 下次贴代码的时候用三个```扩起来。
```
Test
```

**Comment by RustJason** [comment] 2015-10-21 03:02
@ehazlett Is this cause by different version?

**Comment by ehazlett** [comment] 2015-10-21 09:41
Hmm it shouldn't. It looks like a networking issue. Do you have any custom
networking you are doing on the engine?

**Comment by RustJason** [comment] 2015-10-21 11:16
@bing6 @johnny-wang86 Try to ```curl {rethinkdbip}:28015``` and see what happens

**Comment by bing6** [comment] 2015-10-22 00:40
@RustJason 
8080/tcp, 28015/tcp, 29015/tcp 
rethinkdb Port not open up.

I deployed successfully docker 1.8.
docker 1.7 will have this problem.

**Comment by RustJason** [comment] 2015-10-22 02:22
@bing6 But your inspect shows ```28015/tcp``` are exposed, did you try to see the log of rethinkdb to see if it start correctly? And also, you can try to ```docker exec -it ${rethinkdb} bash``  in your controller and ping rethinkdb to see if this error reproduce again

**Comment by bing6** [comment] 2015-10-22 02:40
@RustJason @ehazlett 
This is indeed a network issue.
I found my container within the network can not visit each other.

**Comment by ehazlett** [comment] 2015-10-27 13:29
@bing6 ah ok thanks for the update!  closing,

**Closed by ehazlett** 2015-10-27 13:29 UTC
