### ISSUE TITLE
V3 Automated Deployment:  Wait for Shipyard on xxxxx and goes into a loop for `create , attach, start,wait,delete`

### ISSUE THREAD

**Issue by chengjingtao** [shipyard/shipyard#636] opened 2015-10-15 09:14 UTC
hai,

I got some confusing   when I deploy shipyard v3  on centos 7.
Fllow the document , I used `Automated Deployment` to deploy .
It was ok , but  it went  into a loop  after print  `Waiting for Shipyard on  192.168.5.55:8080`  at last

I start my docker  using `sudo docker daemon &`  on my  remote host .

``` shell
Waiting for Shipyard on  192.168.5.55:8080
.INFO[0929] POST /v1.20/containers/create                
INFO[0929] POST /v1.20/containers/ef32cc02aec3be344e11877e15b41e7b1e43652e155c8bd7d7526184f52c5005/attach?stderr=1&stdout=1&stream=1 
INFO[0929] POST /v1.20/containers/ef32cc02aec3be344e11877e15b41e7b1e43652e155c8bd7d7526184f52c5005/start 
INFO[0931] POST /v1.20/containers/ef32cc02aec3be344e11877e15b41e7b1e43652e155c8bd7d7526184f52c5005/wait 
INFO[0931] GET /v1.20/containers/ef32cc02aec3be344e11877e15b41e7b1e43652e155c8bd7d7526184f52c5005/json 
INFO[0931] DELETE /v1.20/containers/ef32cc02aec3be344e11877e15b41e7b1e43652e155c8bd7d7526184f52c5005?v=1
......
......
......


.INFO[1819] POST /v1.20/containers/create                
INFO[1819] POST /v1.20/containers/3dba009246347bc101d8b47ca570546fc63e8cce21e571ceb2d5a130f4d4ba57/attach?stderr=1&stdout=1&stream=1 
INFO[1819] POST /v1.20/containers/3dba009246347bc101d8b47ca570546fc63e8cce21e571ceb2d5a130f4d4ba57/start 
INFO[1821] POST /v1.20/containers/3dba009246347bc101d8b47ca570546fc63e8cce21e571ceb2d5a130f4d4ba57/wait 
INFO[1821] GET /v1.20/containers/3dba009246347bc101d8b47ca570546fc63e8cce21e571ceb2d5a130f4d4ba57/json 
INFO[1821] DELETE /v1.20/containers/3dba009246347bc101d8b47ca570546fc63e8cce21e571ceb2d5a130f4d4ba57?v=1

......
......
......

```

`create , attach, start,wait , delete` never stop ...

When I visited 192.168.5.55:8080 this time , I got some wrong msgs  .

```
{"data":"No elected primary cluster manager\n","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$BKFH571nq4Nl1rzfytFeouALtuFO/2HFFR3vPNMy95JucnbtBAj2S"}},"statusText":"Internal Server Error"}
```

Did I do something wrong ? 

Thank you for your apply .

**Comment by aa900031** [comment] 2015-10-27 01:57
i have this issue, too

**Comment by ehazlett** [comment] 2015-10-27 13:23
Hmm yes something is wrong with etcd where a master isn't being selected.
Can you paste the Docker version info?

**Comment by bing6** [comment] 2015-10-28 00:29
docker version 1.8.3

**Comment by edcrosbys** [comment] 2015-10-28 14:47
Same OS/docker version and having same problems. I've tried latest, 3.0.0 and 2.0.10.

**Comment by atgf0127** [comment] 2015-10-29 04:07
docker logs shipyard-swarm-manager

ERRO[1188] Leader Election: watch leader channel closed, the store may be unavailable... 
ERRO[1200] Leader Election: watch leader channel closed, the store may be unavailable... 
ERRO[1203] Discovery error: Unexpected watch error      
ERRO[1212] Leader Election: watch leader channel closed, the store may be unavailable... 
INFO[0000] Listening for HTTP                            addr=0.0.0.0:3375 proto=tcp
INFO[0000] Leader Election: Cluster leadership lost     
ERRO[0000] Leader Election: watch leader channel closed, the store may be unavailable...

**Comment by CaryGao** [comment] 2015-11-03 04:06
Same issue,too
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64
```
```
Linux centos71 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x8
6_64 x86_64 x86_64 GNU/Linux
```

**Comment by linecheng** [comment] 2015-11-03 05:20
Yes, my  docker version is 1.8.3, and os is centos 7.
At last ,I changed  `Centos7` to `Ubuntu 14.04` and   deploy  with same methods .  It  works very well .
I think it may be related to the firewalld on  Centos 7 ， I have little experience about firewall ,so I can't analyze more useful information so far.

**Comment by ehazlett** [comment] 2015-11-05 02:32
Yes there are several issues with firewalld on the RedHat distros.  I will
see if I can reproduce.  You can try to disable it to see if that helps.

**Comment by bing6** [comment] 2015-11-09 01:20
@ehazlett 

I found this was caused due to the iptables,
But the network administrator required to use iptables, then how can I do?

**Comment by John-Lin** [comment] 2015-11-09 10:05
Same issue here my environment 
- Ubuntu 14.04
- docker 1.9.0

I cannot deploy container and pull images.

Any suggestions for workaround it?

<img width="1178" alt="screen shot 2015-11-09 at 6 03 34 pm" src="https://cloud.githubusercontent.com/assets/4214069/11030954/450cc852-870c-11e5-80a4-d7126c2b5f09.png">

**Comment by John-Lin** [comment] 2015-11-09 14:45
Oops, after I reboot everything is working fine.

**Comment by dupperinc** [comment] 2015-12-10 19:15
I see the same issue intermittently.

**Comment by TuureKaunisto** [comment] 2016-03-30 14:43
I'm facing the same issue. Are there any workarounds?

**Comment by ehazlett** [comment] 2016-03-30 15:33
Yes you can setup multiple etcd clusters (that is out of scope of Shipyard).  That will give you fault tolerance and leader election to make it available.

**Comment by alainivars** [comment] 2016-05-10 09:49
Same issue with:

-  Ubuntu 14.04
-  Docker version 1.9.1, build a34a1d5

The workaround for me: everything work fine after restart docker service.

**Comment by ehazlett** [comment] 2016-05-17 11:38
Try updating to the latest docker engine. I cannot reproduce on the latest
1.11.1.

**Comment by alainivars** [comment] 2016-05-17 18:38
I don't reproduce it from the restart to now, sorry to can't help. if I reproduce it i will send all the sequence to reproduce it

**Comment by alainivars** [comment] 2016-05-17 19:46
I forgot to say, I work with the latest 1.11.1 now, maybe it's solve the problem

**Comment by xxlaila** [comment] 2017-07-26 08:43
I also encountered this problem。Open http: // <url>: 8080, after the prompts
Error...
{"data":"No elected primary cluster manager\n","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$94UOPiYo2JHuLWX3Aka20O0XFzW48JAG.FoSaO1L61NENZJhWSmcq"}},"statusText":"Internal Server Error"}

**Closed** 2017-10-23 17:53 UTC
Labels: controller, high
