### ISSUE TITLE
Shipyard not found host conainers after power outage

### ISSUE THREAD

**Issue by taiffu** [shipyard/shipyard#642] opened 2015-10-21 06:30 UTC
After power outage and reboot shipyard not any more find containers. In Shipyard web GUI gives followed error.

Error...
{"data":"No elected primary cluster manager\n","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:XXXXXX"}},"statusText":"Internal Server Error"}

Enviroment is running top of latest stabile coreOS version (Stable
766.4.0 with Docker 1.7.1)

**Comment by bing6** [comment] 2015-10-26 01:05
vi /etc/selinux/config
settings SELINUX=disabled

Remember to restart the server.

**Comment by ehazlett** [comment] 2015-10-27 13:28
This seems to be a duplicate of #636 and etcd electing a master.  Thanks for reporting.  We will track this issue there.

**Closed by ehazlett** 2015-10-27 13:28 UTC
