### ISSUE TITLE
Code: System error when starting shipyard image

### ISSUE THREAD

**Issue by ichasepucks** [shipyard/shipyard#554] opened 2015-05-27 22:20 UTC
I'm getting the error below trying to start shipyard using shipyard/deploy as well as the manual method starting rethinkdb and shipyard separately.

I've never tried to use shipyard before.  I don't have much insight into why this is occurring.  The "missing" directory is indeed missing but don't have much else to go on.

OS:
```
3.10.0-123.el7.x86_64 #1 SMP Mon May 5 11:16:57 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux (RHEL 7)
```
Docker:
```
Docker version 1.6.0, build 8aae715/1.6.0
```
Shipyard:
```
latest
```
Command Executed:
```
sudo docker run -it -p 8080:8080 -d --name shipyard --link shipyard-rethinkdb:rethinkdb shipyard/shipyard
```
Docker ps:
```
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                                                                         NAMES
b0e6351ca383        shipyard/shipyard:latest    "/controller"          2 minutes ago                                                                                                         shipyard                  
06a3bbf271df        shipyard/rethinkdb:latest   "/usr/bin/rethinkdb    3 minutes ago       Up 3 minutes        0.0.0.0:32770->8080/tcp, 0.0.0.0:32768->28015/tcp, 0.0.0.0:32769->29015/tcp   shipyard-rethinkdb        
37a3df372f54        shipyard/rethinkdb:latest   "/bin/bash -l"         6 minutes ago       Up 6 minutes        8080/tcp, 28015/tcp, 29015/tcp                                                shipyard-rethinkdb-data
```
Docker log:
```
Timestamp: 2015-05-27 21:48:27.42822901 +0000 GMT
Code: System error

Message: [/usr/bin/tar -cf /var/lib/docker/tmp/b0e6351ca38353cbbfd49c51dc6f2ddd3ae32d0642e85e0f7f1dcd247e733b3b887072747/_tmp.tar -C /var/lib/docker/devicemapper/mnt/b0e6351ca38353cbbfd49c51dc6f2ddd3ae32d0642e85e0f7f1dcd247e733b3b/rootfs/tmp .] failed: /usr/bin/tar: /var/lib/docker/devicemapper/mnt/b0e6351ca38353cbbfd49c51dc6f2ddd3ae32d0642e85e0f7f1dcd247e733b3b/rootfs/tmp: Cannot chdir: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
: exit status 2

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@30
---
1: Init
Package: github.com/docker/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@52
---
2: StartInitialization
Package: github.com/docker/libcontainer.(*LinuxFactory)
File: factory_linux.go@223
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File:
```

**Comment by Madko** [comment] 2015-05-28 11:45
Same here. rethinkdb is pulled and run fine, but no luck with shipyard. Any news about this?

**Comment by Madko** [comment] 2015-05-28 11:57
at least it works with shipyard/shipyard:2.0.8

**Comment by ehazlett** [comment] 2015-05-28 12:48
This is a RedHat specific error.  It looks like either a devicemapper issue
or selinux.  Could you try running with SELinux disabled or a different
base OS to see if that works?

**Comment by Madko** [comment] 2015-05-28 12:55
Selinux was already disabled. Should 2.0.8 be also impacted if it was a SELinux or RH specific error? I could try with debian.

**Comment by ehazlett** [comment] 2015-05-28 13:16
Ah I thought 2.0.8 was a different issue.  That looks like a Docker Engine
the more I look.  Is there any way you could update to the latest 1.6.2?

**Comment by Madko** [comment] 2015-05-28 13:41
not sure there is yet a 1.6.2 offical package, will check that right now. Why do you think it will be fixed in 1.6.2?

**Comment by ehazlett** [comment] 2015-05-28 14:53
Not sure but it appears to be related to docker and not shipyard.

**Comment by ehazlett** [comment] 2015-05-28 14:53
I will see if I can reproduce.

**Comment by Madko** [comment] 2015-05-28 14:57
it's easy to reproduce
starts a vm with centos7 (you can disable selinux: setenforce 0)
yum install docker
systemctl start docker

then follow the shipyard getting started guide.

BTW there is no official package for docker 1.6.2 on RHEL7/CentOS7 so...

**Comment by ichasepucks** [comment] 2015-05-28 15:36
This worked for me upgrading to 1.6.2 however, I'm not so sure this is acceptable for everyone in production environments.  I'm not actually sure what can be done on the Shipyard side to resolve, so I'm not sure if you want to close this bug or not.

```
sudo service docker stop
sudo wget https://get.docker.com/builds/Linux/x86_64/docker-latest -O /usr/bin/docker
```

**Comment by sstarcher** [comment] 2015-05-28 15:45
If you are going to run with latest docker they highly recommend you use.
```wget -qO- https://get.docker.com/ | sh```
as it installs some other dependencies based on your system.

**Comment by ichasepucks** [comment] 2015-05-28 16:31
Looks like this script doesn't support rhel though.

I actually installed using the following for RHEL 7 which first installs the official 1.6.0 and all the dependencies.
```
sudo yum install -y docker
sudo systemctl enable docker.service
sudo wget https://get.docker.com/builds/Linux/x86_64/docker-latest -O /usr/bin/docker
sudo service docker start
```

**Comment by Madko** [comment] 2015-05-29 12:42
I have opened a bug report at RedHat https://bugzilla.redhat.com/show_bug.cgi?id=1226320
I hope they will update to 1.6.2 soon.

**Comment by ehazlett** [comment] 2015-05-29 12:42
Thanks for the info!

**Closed** 2015-09-06 19:27 UTC
