### ISSUE TITLE
shipyard Gateway Timeout","status":504

### ISSUE THREAD

**Issue by sunshibin21** [shipyard/shipyard#693] opened 2015-12-11 03:06 UTC
when i use ui to visit ,i meet this error,
Error...
{"data":"Gateway Timeout","status":504,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/containers/json?all=1","headers":{"Accept":"application/json, text/plain, */*","X-Access-Token":"admin:$2a$10$4WR2qFg/Mv7rpYzuFYgAb.62UzmX8NtZdOalAZNDTm5d6tr9WglBa"}},"statusText":"Gateway Timeout"}

**Comment by ehazlett** [comment] 2015-12-11 15:19
are you getting any errors in the controller?

**Comment by haoyixin** [comment] 2016-01-15 15:06
+1

**Comment by haoyixin** [comment] 2016-01-15 15:06
and no log in container

**Comment by ehazlett** [comment] 2016-02-12 15:03
Closing as I'm not able to reproduce.  I would suggest to check your setup as it appears to have a proxy in front.

**Closed by ehazlett** 2016-02-12 15:03 UTC
